### ISSUE TITLE
Missing script argument in example

### ISSUE THREAD

**Issue by krikru** [vsitzmann/siren#27]
When I run the code `python experiment_scripts/train_img.py --model_type=sine` given in [README.md](https://github.com/vsitzmann/siren/blob/master/README.md), I get the error

```
usage: train_img.py [-h] [-c CONFIG_FILEPATH] [--logging_root LOGGING_ROOT]
                    --experiment_name EXPERIMENT_NAME
                    [--batch_size BATCH_SIZE] [--lr LR]
                    [--num_epochs NUM_EPOCHS]
                    [--epochs_til_ckpt EPOCHS_TIL_CKPT]
                    [--steps_til_summary STEPS_TIL_SUMMARY]
                    [--model_type MODEL_TYPE]
                    [--checkpoint_path CHECKPOINT_PATH]
train_img.py: error: the following arguments are required: --experiment_name
```

**Comment by alexanderbergman7** [comment]
The experiment_name argument is the name of the directory on top of the logging_root folder where logs / results will be written. You can specify whatever name for your experiment that you want, and overwrite it later.
