### ISSUE TITLE
model.cuda() and self.model.load_state_dict(torch.load(opt.checkpoint_path)) are very slow

### ISSUE THREAD

**Issue by Philipflyg** [vsitzmann/siren#44]
When i try to train **sdf**, i found it will take a long time to call **model.cuda()** in file train_sdf.py. (just after printing the model)
Also when testing sdf, **self.model.load_state_dict(torch.load(opt.checkpoint_path))** need a lot of time.

My pytorch and cudatookit are installed according to file environment.yml. ( pytorch=1.5.0=py3.6_cuda10.1.243_cudnn7.6.3_0 )

How can i solve the issue? Is it normal to have such a problem?

**Comment by juanraul8** [comment]
I had a similar issue. I just installed a newer pytorch version where the cuda installed with pytorch matched  with the cuda installed on my system.

**Comment by Philipflyg** [comment]
> I had a similar issue. I just installed a newer pytorch version where the cuda installed with pytorch matched the cuda installed on my system.

tks，i have solved the issue using the same method
